### ISSUE TITLE
XML System Feature Request

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#100]
ReadOrCreate

---

Nice feature, but the boolean now returns if the operation was succesfull. I would like to know what happened, Read, or created? 
Also, It would be great to give some kind of "default / starting content" to this function.
If the file doesn't exist, create it with this structure / XML container. 

---

Example:
ReadHighscores();
If it's read in correctly, extract data from the xml using the "at" method. If this XML is just created however, it's empty, resulting in a crash!

**Comment by GlenDC** [comment]
Ok this problem is resolved. 
- There is an extra parameter called rootName: this will be the name of root in case it created a new file
- The return value is a uint8. 
  - 0 means something went wrong
  - 1 means the file has been read
  - 2 means that a new file has been created
