### ISSUE TITLE
ReadOrCreate Android Bug

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#101]
This doesn't seem to work properly on Android. The is a warning log: 
"Couldn't open the binary file '/data/data/com.stargame/files/NameOfXML.bin' 

After the warning the app crashes.

**Comment by GlenDC** [comment]
Ok the warning won't  be given anymore, as it is confusing in case of ReadOrCreate.
The app crash is not normal though, so shouldn't have to do sth with what you are reporting. Closing this issue.

**Comment by NuclearCookie** [comment]
Issue isnt fixed

**Comment by NuclearCookie** [comment]
Sorry, it is fixed, the issue is something else
