### ISSUE TITLE
Change the namespace WindowsConsole to namespace star_w ?

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#102]
Since we have a namespace star_a for android specific functions...

**Comment by GlenDC** [comment]
Good idea :) The idea of putting this android stuff in a separate namespace is was to hide it from the user. As it was not meant for the user it seemed like a bad idea to waste the public star space with functions/ classes / code he didn't needed to use in the first place. So I'll apply this ;)
