### ISSUE TITLE
Add feature : Disable/Remove object from physics

### ISSUE THREAD

**Issue by MKytta** [GlenDC/StarEngine#33]
Troubles with dual deletion, breaking the game inside a for loop.
Possible solution would be to disable the collidercomponent and make the sprite invisible instead of deleting it there. We should delete this at the bottom line, like everything else.

**Comment by NuclearCookie** [comment]
Could you give more explanation to what you are doing? If you remove an object, it also gets removed from the physics system, so please elaborate on the way you try to remove the object. 

Also, dual deletion? That's most likely your own fault, unless it's not a dual deletion but an invalidation of the iterators of the container through which we are looping. 

Please post some code sample showing where it goes wrong, thanks!

**Comment by NuclearCookie** [comment]
Inactive and unknow issue. closed
