### ISSUE TITLE
XML doesnt read inlines

### ISSUE THREAD

**Issue by Syvion** [GlenDC/StarEngine#53]
When having a string in an xml file for example : "This string\nShould be newlined"
will actualy show the \n in the string and not newline it.

Using the xml newlining breaks the code : for example
<text> This string
           Should be newlines</text>

That will break the code, normaly reading this xml file will automaticaly have a linebreak where you start a new line (so after string).

The break happens in Spritebatch.cpp
in this code : http://pastebin.com/FkGb0pp4
The "horOffset" goes out of bounds due to line_counter being to big.

**Comment by GlenDC** [comment]
Newlines do get read and parsed correctly. That bug is also fixed, but not yed pushed as it is on the branch of NuclearCookie and Vanatis. It is part of the big spritebatch update, expect a push around wednesday.
