### ISSUE TITLE
Confusing functions UISystem

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#55]
It's confusing that the translate functions are different depending on the alignment. 
With top alignment, a positive translate is downwards... with center it's upwards.. 
Stick to the engine convention please.

**Comment by GlenDC** [comment]
Correct that this is probably confusing. Would be nice if you would have told that long time ago, before anyone used it when I presented the UI System for the entire programmers time. This issue will be resolved in the next update.
