### ISSUE TITLE
UISlider Enhancement

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#57]
A range limit to the slider would be nice.

now the slider takes the full range of the background image like this:
...........................
|.........................|
| O-------------------O|
|.........................|

as far as i can tell, there is no support to limit the range of the slider so that it doesn't go to the edges of the background image.
..........................
|.........................|
|....O------------O....|
|.........................|

**Comment by GlenDC** [comment]
Resolved in next update
