### ISSUE TITLE
Provide rotate functionality in UI

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#58]
would be nice to have a rotate / mirror function in for example the button.

---

Mirroring will be implemented in the new spritebatching but the UI should support this

**Comment by GlenDC** [comment]
Mirroring is already possible via the normal transformComponent->Scale functionality. The rotation of UI objects will be reviewed and resolved if needed in the next update.

**Comment by NuclearCookie** [comment]
I agree about the mirroring through scaling, however, if you use scale, the image flips around the axises aswell. So it should be wrapped in a function to make it more easy to use. 
![untitled-1](https://f.cloud.github.com/assets/5354914/1733056/ea4e333c-632d-11e3-81c3-744a9278be2e.png)

**Comment by GlenDC** [comment]
Resolved mirror part in next update

**Comment by GlenDC** [comment]
Ok rotation part is resolved to. Just all every object you can just rotate via the transform component. In case you want to align an UIObject you now have a bool parameter that defines if the center will be redefined or not. By default this is true. So if you have set your own center pointer for that specific object you probably don't want the center-point to be redefined as you probably want to rotate around your personal defined center-point. All of this should solve this issue for good.
